export class NoFallbackError extends Error {
  constructor() {
    super()
    this.message =
      'A dynamic route parameter was not generated by `generateStaticParams` while `dynamicParams = false`.'
  }
}
